In [8]:
import numpy as np
import pandas as pd
import datetime
from datetime import datetime, date
import matplotlib.pyplot as plt
%matplotlib inline

# Задаем некоторые опции pandas, которые настраивают вывод
# вывод Series и DataFrame в виде текста, а не HTML
pd.set_option('display.notebook_repr_html', False)
# максимальное число выводимыч строк и столбцов
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 10)
# максимальное кол-во символов в каждой строке
pd.set_option('display.width', 80)

### Проверка скорости работы NumPy arrays

In [12]:
py_ar = range(1000)
%timeit [i**2 for i in py_ar]

num_ar =  np.arange(1000)
%timeit num_ar**2

196 µs ± 602 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
944 ns ± 8.53 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
%%time
num_ar =  np.arange(1000)
num_ar**2

CPU times: user 51 µs, sys: 0 ns, total: 51 µs
Wall time: 42 µs


In [38]:
%%time
py_ar = range(1000)
[i**2 for i in py_ar]

CPU times: user 344 µs, sys: 3 µs, total: 347 µs
Wall time: 351 µs


### Помощь по библиотекам

In [39]:
np.array?

In [41]:
np.con*?

In [42]:
pd.con*?

### Creating arrays

##### 1D

In [50]:
a = np.array([0, 1, 2, 3, 4])
# a
# a.ndim
# a.shape
len(a)

5

##### 2D-3D

In [62]:
c = np.array([[1, 2, 3], [4,5,6]])
# c
# c.shape
# c.ndim
# len(c)
d = np.array([[1,3,5], [7,7,7], [2,4,6]])
d
b = np.array([[[1],[2]],[[3],[4]]])
b.shape

(3, 3)

#### Наполнение матриц

In [63]:
a = np.arange(10) # 0 .. n-1  (!)
b = np.arange(1, 9, 2) # start, end (exclusive), step
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [64]:
c = np.linspace(0, 1, 6)   # start, end, num-points
d = np.linspace(0, 1, 5, endpoint=False)
print(c)
print(d)

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]


In [65]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
b = np.zeros((2, 2))
c = np.eye(3)
d = np.diag(np.array([1, 2, 3, 4]))
print(a)
print(b)
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [76]:
a = np.random.rand(4)       # uniform in [0, 1]
b = np.random.randn(4)      # Gaussian
np.random.seed(1234)        # Setting the random seed
print(a)
print(b)

[0.19151945 0.62210877 0.43772774 0.78535858]
[-0.72058873  0.88716294  0.85958841 -0.6365235 ]


In [79]:
np.empty

<function numpy.core.multiarray.empty>

In [4]:
pd.get_option('display.max_rows')

12

In [3]:
pd.set_option('max_r', 12)

In [6]:
df = pd.DataFrame(np.random.randn(7,2))
df

          0         1
0 -2.759481 -1.285646
1  0.329240  0.145871
2 -1.104701  2.032614
3 -0.215042  0.622902
4 -0.954375  0.510244
5  1.230378 -0.400048
6 -0.198084  0.621719

## Объект Series

In [11]:
s = pd.Series([1, 2, 3, 4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [19]:
s[[1, 3]]

1    2
3    4
dtype: int64

In [ ]:
# Series 